name: items_proj
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  #State management
  get: ^4.6.5
  #ui
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  flutter_screenutil: ^5.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  #linter
  dart_code_metrics:
    git:
      url: https://github.com/dart-code-checker/dart-code-metrics.git

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Geomanist
      fonts:
        - asset: fonts/Geomanist-Light.ttf
          weight: 300
        - asset: fonts/Geomanist-Regular.ttf
          weight: 400
        - asset: fonts/Geomanist-Medium.ttf
          weight: 600
        - asset: fonts/Geomanist-Bold.ttf
          weight: 700

#localization (1) install intl extension (2) 'Ctrl + S' to update intl.arb
flutter_intl:
  enabled: true

#assets generator (1) 'dart pub global activate flutter_gen' (2) 'fluttergen -c pubspec.yaml' to generate
flutter_gen:
  output: lib/core/theme/
